version: 2
 
sources:
  - name: coffee_shop
    project: analytics-engineers-club
    description: This is a description of the coffee_shop_pernilla project
    freshness:
      error_after:
        count: 12
        period: hour
    loaded_at_field: created_at

    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: order_items
        columns:
          - name: id
            data_type: integer
            tests:
              - unique
              - not_null
          - name: order_id
            data_type: integer
          - name: product_id
            data_type: integer

      - name: product_prices
        columns:
          - name: id
            data_type: integer
            tests:
              - unique
              - not_null
          - name: product_id
            data_type: integer
          - name: price
            data_type: integer
          - name: created_at
            data_type: timestamp
          - name: ended_at
            data_type: timestamp
            
      - name: products
        columns:
          - name: id
            data_type: integer
            tests:
              - unique
              - not_null
          - name: name
            data_type: string
          - name: category
            data_type: string
          - name: created_at
            data_type: timestamp